/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Everforest API 文件
 * 北14森森不息-露營活動票務系統的 API 文件
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type GetMemberProfile200DataMember = {
  id?: string;
  username?: string;
  firstname?: string;
  lastname?: string;
  email?: string;
  role?: string;
};

export type GetMemberProfile200Data = {
  member?: GetMemberProfile200DataMember;
};

export type GetMemberProfile200 = {
  status?: string;
  message?: string;
  data?: GetMemberProfile200Data;
};

export type GetMemberProfile400 = {
  status?: boolean;
  message?: string;
};

/**
 * 用戶的性別
 */
export type PatchMemberProfileBodyGender = typeof PatchMemberProfileBodyGender[keyof typeof PatchMemberProfileBodyGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PatchMemberProfileBodyGender = {
  男: '男',
  女: '女',
} as const;

export type PatchMemberProfileBody = {
  /** 用戶的名字 */
  firstname?: string;
  /** 用戶的姓氏 */
  lastname?: string;
  /** 用戶的用戶名 */
  username?: string;
  /** 用戶的出生日期 */
  birth?: string;
  /** 用戶的性別 */
  gender?: PatchMemberProfileBodyGender;
  /** 用戶的頭像照片 URL */
  photo_url?: string;
};

export type PatchMemberProfile200 = {
  status?: string;
  message?: string;
};

export type PatchMemberProfile400 = {
  status?: boolean;
  message?: string;
};

export type PostMemberProfileAvatarBody = {
  /** 上傳的頭像圖片 */
  file?: Blob;
};

export type PostMemberProfileAvatar200Data = {
  photo_url?: string;
};

export type PostMemberProfileAvatar200 = {
  status?: string;
  message?: string;
  data?: PostMemberProfileAvatar200Data;
};

export type PostMemberProfileAvatar400 = {
  status?: string;
  message?: string;
};

export type PostMemberProfileAvatar404 = {
  status?: string;
  message?: string;
};

/**
 * 取得目前登入會員的詳細資料，包含關聯的會員角色資訊。

📌 僅限已登入且身份為 `member` 的會員存取。

⚠️ 請確保請求附帶身份驗證 Cookie（access_token）。

 * @summary 取得會員資料
 */
export const getMemberProfile = <TData = AxiosResponse<GetMemberProfile200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/member/profile`,options
    );
  }

/**
 * 修改目前登入會員的詳細資料，包含關聯的會員角色資訊。

📌 僅限已登入且身份為 `member` 的會員存取。

⚠️ 請確保請求附帶身份驗證 Cookie（access_token）。

 * @summary 更新會員資料
 */
export const patchMemberProfile = <TData = AxiosResponse<PatchMemberProfile200>>(
    patchMemberProfileBody: PatchMemberProfileBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/member/profile`,
      patchMemberProfileBody,options
    );
  }

/**
 * 上傳並更新會員頭像，圖片限制大小為 2MB。

📌 僅限已登入且身份為 `member` 的會員存取。

⚠️ 請確保請求附帶身份驗證 Cookie（access_token）。

 * @summary 上傳會員頭像
 */
export const postMemberProfileAvatar = <TData = AxiosResponse<PostMemberProfileAvatar200>>(
    postMemberProfileAvatarBody: PostMemberProfileAvatarBody, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
if(postMemberProfileAvatarBody.file !== undefined) {
 formData.append(`file`, postMemberProfileAvatarBody.file)
 }

    return axios.post(
      `/member/profile/avatar`,
      formData,options
    );
  }

export type GetMemberProfileResult = AxiosResponse<GetMemberProfile200>
export type PatchMemberProfileResult = AxiosResponse<PatchMemberProfile200>
export type PostMemberProfileAvatarResult = AxiosResponse<PostMemberProfileAvatar200>
