/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Everforest API 文件
 * 北14森森不息-露營活動票務系統的 API 文件
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PostApiV1MetaEventTagsBody = {
  name: string;
};

export type PostApiV1MetaEventTags201DataEventTag = {
  id?: string;
  name?: string;
};

export type PostApiV1MetaEventTags201Data = {
  eventTag?: PostApiV1MetaEventTags201DataEventTag;
};

export type PostApiV1MetaEventTags201 = {
  status?: string;
  message?: string;
  data?: PostApiV1MetaEventTags201Data;
};

export type PostApiV1MetaEventTags400 = {
  status?: string;
  message?: string;
};

export type PostApiV1MetaEventTags409 = {
  status?: string;
  message?: string;
};

export type PostApiV1MetaEventTags500 = {
  status?: string;
  message?: string;
};

export type GetApiV1MetaEventTags200DataEventTagsItem = {
  id?: string;
  name?: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  level?: string | null;
  created_at?: string;
};

export type GetApiV1MetaEventTags200Data = {
  eventTags?: GetApiV1MetaEventTags200DataEventTagsItem[];
};

export type GetApiV1MetaEventTags200 = {
  status?: string;
  message?: string;
  data?: GetApiV1MetaEventTags200Data;
};

export type GetApiV1MetaEventTags500 = {
  status?: string;
  message?: string;
};

/**
 * ⚠️ 僅限已登入的主辦方使用，用來建立活動標籤。

✅ 建立一個新的活動標籤名稱(至少4個字)，標籤名稱必須唯一。

 * @summary 建立活動標籤
 */
export const postApiV1MetaEventTags = <TData = AxiosResponse<PostApiV1MetaEventTags201>>(
    postApiV1MetaEventTagsBody: PostApiV1MetaEventTagsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/meta/event-tags`,
      postApiV1MetaEventTagsBody,options
    );
  }

/**
 * 取得目前系統中所有活動標籤清單，供活動建立與標籤選擇使用。
此 API 為公開 API，不需要登入驗證，前台與後台皆可使用。

 * @summary 取得所有活動標籤（公開）
 */
export const getApiV1MetaEventTags = <TData = AxiosResponse<GetApiV1MetaEventTags200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/meta/event-tags`,options
    );
  }

export type PostApiV1MetaEventTagsResult = AxiosResponse<PostApiV1MetaEventTags201>
export type GetApiV1MetaEventTagsResult = AxiosResponse<GetApiV1MetaEventTags200>
