/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * Everforest API 文件
 * 北14森森不息-露營活動票務系統的 API 文件
 * OpenAPI spec version: 1.0.0
 */
import axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type PostApiV1EventsBody = {
  title: string;
  address: string;
  description: string;
  start_time: string;
  end_time: string;
  max_participants: number;
  cancel_policy: string;
  /** @nullable */
  registration_open_time?: string | null;
  /** @nullable */
  registration_close_time?: string | null;
  /** @nullable */
  latitude?: number | null;
  /** @nullable */
  longitude?: number | null;
};

export type PostApiV1Events201DataEvent = {
  id?: string;
  host_info_id?: string;
  title?: string;
  status?: string;
  active?: string;
};

export type PostApiV1Events201Data = {
  event?: PostApiV1Events201DataEvent;
};

export type PostApiV1Events201 = {
  status?: string;
  message?: string;
  data?: PostApiV1Events201Data;
};

export type PostApiV1Events400 = {
  status?: string;
  message?: string;
};

export type PostApiV1Events401 = {
  status?: string;
  message?: string;
};

export type PostApiV1Events403 = {
  status?: string;
  message?: string;
};

export type PostApiV1Events409 = {
  status?: string;
  message?: string;
};

export type PostApiV1Events500 = {
  status?: string;
  message?: string;
};

export type GetApiV1EventsParams = {
/**
 * 活動開始時間（ISO 格式）
 */
startTime?: string;
/**
 * 活動結束時間（ISO 格式）
 */
endTime?: string;
/**
 * 活動地點關鍵字（模糊搜尋）
 */
location?: string;
/**
 * 最低價格
 */
minPrice?: number;
/**
 * 最高價格
 */
maxPrice?: number;
/**
 * 人數關鍵字
 */
people?: number;
/**
 * 當前頁碼（預設為 1）
 */
page?: number;
/**
 * 每頁筆數（預設為 10）
 */
per?: number;
/**
 * 排序方式（asc 或 desc）
 */
sort?: GetApiV1EventsSort;
};

export type GetApiV1EventsSort = typeof GetApiV1EventsSort[keyof typeof GetApiV1EventsSort];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1EventsSort = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type GetApiV1Events200DataPagination = {
  page?: number;
  per?: number;
  total?: number;
  total_pages?: number;
  sort?: string;
};

export type GetApiV1Events200DataEventsItem = {
  id?: string;
  title?: string;
  start_time?: string;
  end_time?: string;
  address?: string;
  price?: string;
  photos?: string[];
  tags?: string[];
};

export type GetApiV1Events200Data = {
  pagination?: GetApiV1Events200DataPagination;
  events?: GetApiV1Events200DataEventsItem[];
};

export type GetApiV1Events200 = {
  status?: string;
  message?: string;
  data?: GetApiV1Events200Data;
};

export type GetApiV1Events400 = {
  status?: string;
  message?: string;
};

export type GetApiV1Events500 = {
  status?: string;
  message?: string;
};

export type PatchApiV1EventsEventIdNoticesTagsBodyNoticesItem = {
  type?: string;
  content?: string;
};

export type PatchApiV1EventsEventIdNoticesTagsBody = {
  tagIds?: string[];
  notices?: PatchApiV1EventsEventIdNoticesTagsBodyNoticesItem[];
};

export type PatchApiV1EventsEventIdNoticesTags200 = { [key: string]: unknown };

export type PatchApiV1EventsEventIdNoticesTags400 = { [key: string]: unknown };

export type PatchApiV1EventsEventIdNoticesTags401 = { [key: string]: unknown };

export type PatchApiV1EventsEventIdNoticesTags403OneOf = { [key: string]: unknown };

export type PatchApiV1EventsEventIdNoticesTags403OneOfTwo = { [key: string]: unknown };

export type PatchApiV1EventsEventIdNoticesTags403 = PatchApiV1EventsEventIdNoticesTags403OneOf | PatchApiV1EventsEventIdNoticesTags403OneOfTwo;

export type PatchApiV1EventsEventIdNoticesTags500 = { [key: string]: unknown };

export type PostApiV1EventsEventIdImagesParams = {
/**
 * 圖片類型，可為 `cover`（封面圖）或 `detail`（詳情圖）
 */
type: PostApiV1EventsEventIdImagesType;
};

export type PostApiV1EventsEventIdImagesType = typeof PostApiV1EventsEventIdImagesType[keyof typeof PostApiV1EventsEventIdImagesType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiV1EventsEventIdImagesType = {
  cover: 'cover',
  detail: 'detail',
} as const;

export type PostApiV1EventsEventIdImagesBody = {
  /** 上傳的圖片檔案（最多 3 張） */
  file?: Blob[];
  /** 圖片對應的描述內容（只有 `type=detail` 時使用） */
  descriptions?: string[];
};

export type PostApiV1EventsEventIdImages201DataItemType = typeof PostApiV1EventsEventIdImages201DataItemType[keyof typeof PostApiV1EventsEventIdImages201DataItemType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PostApiV1EventsEventIdImages201DataItemType = {
  cover: 'cover',
  detail: 'detail',
} as const;

export type PostApiV1EventsEventIdImages201DataItem = {
  imageId?: string;
  event_info_id?: string;
  imageUrl?: string;
  type?: PostApiV1EventsEventIdImages201DataItemType;
  /** @nullable */
  description?: string | null;
};

export type PostApiV1EventsEventIdImages201 = {
  status?: string;
  message?: string;
  data?: PostApiV1EventsEventIdImages201DataItem[];
};

export type PostApiV1EventsEventIdImages400 = {
  status?: string;
  message?: string;
};

export type PostApiV1EventsEventIdImages401 = {
  status?: string;
  message?: string;
};

export type PostApiV1EventsEventIdImages403 = {
  status?: string;
  message?: string;
};

export type PostApiV1EventsEventIdPlansBodyPlansItemAddonsItem = {
  /** 加購品名稱 */
  name?: string;
  /** 加購品價格 */
  price?: number;
};

export type PostApiV1EventsEventIdPlansBodyPlansItem = {
  /** 方案名稱 */
  title: string;
  /** 原價 */
  price: number;
  /** 折扣價（可省略） */
  discounted_price?: number;
  /** 方案內容陣列 */
  contents?: string[];
  addons?: PostApiV1EventsEventIdPlansBodyPlansItemAddonsItem[];
};

export type PostApiV1EventsEventIdPlansBody = {
  plans?: PostApiV1EventsEventIdPlansBodyPlansItem[];
};

export type GetApiV1EventsEventIdPlans200DataPlansItemAddonsItem = {
  name?: string;
  price?: number;
};

export type GetApiV1EventsEventIdPlans200DataPlansItem = {
  id?: string;
  title?: string;
  price?: number;
  discounted_price?: number;
  contents?: string[];
  addons?: GetApiV1EventsEventIdPlans200DataPlansItemAddonsItem[];
};

export type GetApiV1EventsEventIdPlans200Data = {
  event_info_id?: string;
  plans?: GetApiV1EventsEventIdPlans200DataPlansItem[];
};

export type GetApiV1EventsEventIdPlans200 = {
  status?: string;
  message?: string;
  data?: GetApiV1EventsEventIdPlans200Data;
};

export type PatchApiV1EventsEventIdPlansBodyPlansItemAddonsItem = {
  name?: string;
  price?: number;
};

export type PatchApiV1EventsEventIdPlansBodyPlansItem = {
  /** 若為更新請帶入方案 ID */
  id?: string;
  title?: string;
  price?: number;
  discounted_price?: number;
  contents?: string[];
  addons?: PatchApiV1EventsEventIdPlansBodyPlansItemAddonsItem[];
};

export type PatchApiV1EventsEventIdPlansBody = {
  plans?: PatchApiV1EventsEventIdPlansBodyPlansItem[];
};

export type PatchApiV1EventsEventIdPublish200Data = {
  eventId?: string;
  status?: string;
};

export type PatchApiV1EventsEventIdPublish200 = {
  status?: string;
  message?: string;
  data?: PatchApiV1EventsEventIdPublish200Data;
};

export type GetApiV1EventsRecommend200Data = { [key: string]: unknown };

export type GetApiV1EventsRecommend200 = {
  status?: string;
  message?: string;
  data?: GetApiV1EventsRecommend200Data;
};

export type GetApiV1EventsRecommend500 = {
  status?: string;
  message?: string;
};

/**
 * 活動詳細資料
 */
export type GetApiV1EventsEventId200Data = { [key: string]: unknown };

export type GetApiV1EventsEventId200 = {
  status?: string;
  message?: string;
  /** 活動詳細資料 */
  data?: GetApiV1EventsEventId200Data;
};

export type GetApiV1EventsMapLiveMap200DataEventsItemStatus = typeof GetApiV1EventsMapLiveMap200DataEventsItemStatus[keyof typeof GetApiV1EventsMapLiveMap200DataEventsItemStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetApiV1EventsMapLiveMap200DataEventsItemStatus = {
  preparing: 'preparing',
  registering: 'registering',
  expired: 'expired',
  full: 'full',
} as const;

export type GetApiV1EventsMapLiveMap200DataEventsItem = {
  id?: string;
  title?: string;
  latitude?: number;
  longitude?: number;
  status?: GetApiV1EventsMapLiveMap200DataEventsItemStatus;
  start_time?: string;
  end_time?: string;
  address?: string;
};

export type GetApiV1EventsMapLiveMap200Data = {
  events?: GetApiV1EventsMapLiveMap200DataEventsItem[];
};

export type GetApiV1EventsMapLiveMap200 = {
  status?: string;
  message?: string;
  data?: GetApiV1EventsMapLiveMap200Data;
};

export type GetApiV1EventsMapLiveMap500 = {
  status?: string;
  message?: string;
};

/**
 * 僅限已登入的主辦方使用，用來建立活動基本資料。

⚠️ 注意：主辦方需先建立 Host_Info 資料，否則會回傳 403。

✅ 成功後會儲存為active為'draft'狀態，可後續補上圖片、方案、提醒等資料。

 * @summary 建立一筆新的活動
 */
export const postApiV1Events = <TData = AxiosResponse<PostApiV1Events201>>(
    postApiV1EventsBody: PostApiV1EventsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/events`,
      postApiV1EventsBody,options
    );
  }

/**
 * @summary 取得公開活動列表（支援篩選與分頁）
 */
export const getApiV1Events = <TData = AxiosResponse<GetApiV1Events200>>(
    params?: GetApiV1EventsParams, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/events`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 主辦方取得自己的活動詳情
 */
export const getApiV1EventsEventIdHost = <TData = AxiosResponse<void>>(
    eventId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/events/${eventId}/host`,options
    );
  }

/**
 * 主辦方更新指定活動的行前提醒與標籤。若陣列為空則代表清除所有設定。
 * @summary 更新活動的行前提醒與標籤
 */
export const patchApiV1EventsEventIdNoticesTags = <TData = AxiosResponse<PatchApiV1EventsEventIdNoticesTags200>>(
    eventId: string,
    patchApiV1EventsEventIdNoticesTagsBody: PatchApiV1EventsEventIdNoticesTagsBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/events/${eventId}/notices-tags`,
      patchApiV1EventsEventIdNoticesTagsBody,options
    );
  }

/**
 * 需登入並擁有活動主辦權限。可上傳最多 3 張封面圖或詳情圖，僅支援 JPG / PNG 格式。
 * @summary 上傳活動圖片（封面圖或詳情圖）
 */
export const postApiV1EventsEventIdImages = <TData = AxiosResponse<PostApiV1EventsEventIdImages201>>(
    eventId: string,
    postApiV1EventsEventIdImagesBody: PostApiV1EventsEventIdImagesBody,
    params: PostApiV1EventsEventIdImagesParams, options?: AxiosRequestConfig
 ): Promise<TData> => {const formData = new FormData();
if(postApiV1EventsEventIdImagesBody.file !== undefined) {
 postApiV1EventsEventIdImagesBody.file.forEach(value => formData.append(`file`, value));
 }
if(postApiV1EventsEventIdImagesBody.descriptions !== undefined) {
 postApiV1EventsEventIdImagesBody.descriptions.forEach(value => formData.append(`descriptions`, value));
 }

    return axios.post(
      `/api/v1/events/${eventId}/images`,
      formData,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }

/**
 * @summary 建立活動方案（含內容與加購品）
 */
export const postApiV1EventsEventIdPlans = <TData = AxiosResponse<void>>(
    eventId: string,
    postApiV1EventsEventIdPlansBody: PostApiV1EventsEventIdPlansBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.post(
      `/api/v1/events/${eventId}/plans`,
      postApiV1EventsEventIdPlansBody,options
    );
  }

/**
 * @summary 取得活動方案（含內容與加購品）
 */
export const getApiV1EventsEventIdPlans = <TData = AxiosResponse<GetApiV1EventsEventIdPlans200>>(
    eventId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/events/${eventId}/plans`,options
    );
  }

/**
 * @summary 批次更新或新增活動方案
 */
export const patchApiV1EventsEventIdPlans = <TData = AxiosResponse<void>>(
    eventId: string,
    patchApiV1EventsEventIdPlansBody: PatchApiV1EventsEventIdPlansBody, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/events/${eventId}/plans`,
      patchApiV1EventsEventIdPlansBody,options
    );
  }

/**
 * @summary 將活動從草稿狀態上架為已發布
 */
export const patchApiV1EventsEventIdPublish = <TData = AxiosResponse<PatchApiV1EventsEventIdPublish200>>(
    eventId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.patch(
      `/api/v1/events/${eventId}/publish`,undefined,options
    );
  }

/**
 * 根據活動地址中的縣市名稱進行分類，回傳所有已發布的推薦活動。
 * @summary 取得推薦活動，依縣市分類
 */
export const getApiV1EventsRecommend = <TData = AxiosResponse<GetApiV1EventsRecommend200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/events/recommend`,options
    );
  }

/**
 * @summary 取得公開活動詳情（僅限已上架活動）
 */
export const getApiV1EventsEventId = <TData = AxiosResponse<GetApiV1EventsEventId200>>(
    eventId: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/events/${eventId}`,options
    );
  }

/**
 * 回傳所有 `active = published` 的活動，包含標題、地點、狀態與起訖時間等資訊，用於地圖顯示。
 * @summary 取得所有上架活動的地理座標資訊
 */
export const getApiV1EventsMapLiveMap = <TData = AxiosResponse<GetApiV1EventsMapLiveMap200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.get(
      `/api/v1/events/map/live_map`,options
    );
  }

export type PostApiV1EventsResult = AxiosResponse<PostApiV1Events201>
export type GetApiV1EventsResult = AxiosResponse<GetApiV1Events200>
export type GetApiV1EventsEventIdHostResult = AxiosResponse<void>
export type PatchApiV1EventsEventIdNoticesTagsResult = AxiosResponse<PatchApiV1EventsEventIdNoticesTags200>
export type PostApiV1EventsEventIdImagesResult = AxiosResponse<PostApiV1EventsEventIdImages201>
export type PostApiV1EventsEventIdPlansResult = AxiosResponse<void>
export type GetApiV1EventsEventIdPlansResult = AxiosResponse<GetApiV1EventsEventIdPlans200>
export type PatchApiV1EventsEventIdPlansResult = AxiosResponse<void>
export type PatchApiV1EventsEventIdPublishResult = AxiosResponse<PatchApiV1EventsEventIdPublish200>
export type GetApiV1EventsRecommendResult = AxiosResponse<GetApiV1EventsRecommend200>
export type GetApiV1EventsEventIdResult = AxiosResponse<GetApiV1EventsEventId200>
export type GetApiV1EventsMapLiveMapResult = AxiosResponse<GetApiV1EventsMapLiveMap200>
